version: "3.9"

services:
  fe-unit-app:
    build: .
    container_name: fe-unit-app
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

    depends_on: []
